/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Data.Aeropuerto;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author juansevargas
 */
public class ventanaInicio extends javax.swing.JFrame {

    /**
     * Creates new form ventanaInicio
     */
    public ventanaInicio() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabelBienvenida = new javax.swing.JLabel();
        jLabelSeleccione = new javax.swing.JLabel();
        jMenuAeropuertos = new javax.swing.JComboBox<>();
        jButtonSeleccionarInicio = new javax.swing.JButton();
        jButtonSalirInicio = new javax.swing.JButton();
        jButtonAcerca = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Mshtakan", 0, 60)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("LÜFTET");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 370, 120));

        jLabelBienvenida.setFont(new java.awt.Font("Seravek", 0, 36)); // NOI18N
        jLabelBienvenida.setForeground(new java.awt.Color(222, 222, 243));
        jLabelBienvenida.setText("Bienvenido");
        getContentPane().add(jLabelBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 220, 60));

        jLabelSeleccione.setFont(new java.awt.Font("Seravek", 0, 18)); // NOI18N
        jLabelSeleccione.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSeleccione.setText("Seleccione aeropuerto");
        getContentPane().add(jLabelSeleccione, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 180, 50));

        jMenuAeropuertos.setFont(new java.awt.Font("Seravek", 0, 13)); // NOI18N
        jMenuAeropuertos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aeropuerto Internacional El Dorado - Bogotá, Colombia", "Aeropuerto Internacional John F. Kennedy - Nueva York, EE.UU" }));
        jMenuAeropuertos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAeropuertosActionPerformed(evt);
            }
        });
        getContentPane().add(jMenuAeropuertos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 550, 30));

        jButtonSeleccionarInicio.setFont(new java.awt.Font("Seravek", 0, 13)); // NOI18N
        jButtonSeleccionarInicio.setText("Seleccionar");
        jButtonSeleccionarInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeleccionarInicioActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSeleccionarInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, 120, -1));

        jButtonSalirInicio.setBackground(new java.awt.Color(204, 204, 204));
        jButtonSalirInicio.setFont(new java.awt.Font("Seravek", 2, 13)); // NOI18N
        jButtonSalirInicio.setText("SALIR");
        jButtonSalirInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirInicioActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalirInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 521, 80, 30));

        jButtonAcerca.setFont(new java.awt.Font("Seravek", 2, 13)); // NOI18N
        jButtonAcerca.setText("Acerca de la app");
        jButtonAcerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAcercaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAcerca, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 480, 120, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectResources/Flughafen-Fernbahnsteig_Fahrstuhl-Frankfurt_am_Main.JPG"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirInicioActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirInicioActionPerformed

    private void jButtonSeleccionarInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeleccionarInicioActionPerformed
        // TODO add your handling code here:
        int indiceMenu = this.jMenuAeropuertos.getSelectedIndex();
        
        if(indiceMenu == 0)
        {
            VentanaAeropuerto0 a = new VentanaAeropuerto0();
            a.setVisible(true);
            this.setVisible(false);
        }else if(indiceMenu == 1)
        {
            JOptionPane.showMessageDialog(null, "Lo sentimos, actualmente no disponible", "Advertencia", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_jButtonSeleccionarInicioActionPerformed

    private void jButtonAcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAcercaActionPerformed
        // TODO add your handling code here:
        VentanaAcercaDe ac = new VentanaAcercaDe();
        ac.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonAcercaActionPerformed

    private void jMenuAeropuertosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAeropuertosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuAeropuertosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaInicio().setVisible(true);
            }
        });
    }

    public JButton getjButtonAcerca() {
        return jButtonAcerca;
    }

    public void setjButtonAcerca(JButton jButtonAcerca) {
        this.jButtonAcerca = jButtonAcerca;
    }

    public JButton getjButtonSalirInicio() {
        return jButtonSalirInicio;
    }

    public void setjButtonSalirInicio(JButton jButtonSalirInicio) {
        this.jButtonSalirInicio = jButtonSalirInicio;
    }

    public JButton getjButtonSeleccionarInicio() {
        return jButtonSeleccionarInicio;
    }

    public void setjButtonSeleccionarInicio(JButton jButtonSeleccionarInicio) {
        this.jButtonSeleccionarInicio = jButtonSeleccionarInicio;
    }

    public JLabel getjLabelBienvenida() {
        return jLabelBienvenida;
    }

    public void setjLabelBienvenida(JLabel jLabelBienvenida) {
        this.jLabelBienvenida = jLabelBienvenida;
    }

    public JLabel getjLabelFondo() {
        return jLabelFondo;
    }

    public void setjLabelFondo(JLabel jLabelFondo) {
        this.jLabelFondo = jLabelFondo;
    }

    public JLabel getjLabelSeleccione() {
        return jLabelSeleccione;
    }

    public void setjLabelSeleccione(JLabel jLabelSeleccione) {
        this.jLabelSeleccione = jLabelSeleccione;
    }

    public JLabel getjLabelTitulo() {
        return jLabelTitulo;
    }

    public void setjLabelTitulo(JLabel jLabelTitulo) {
        this.jLabelTitulo = jLabelTitulo;
    }

    public JComboBox<String> getjMenuAeropuertos() {
        return jMenuAeropuertos;
    }

    public void setjMenuAeropuertos(JComboBox<String> jMenuAeropuertos) {
        this.jMenuAeropuertos = jMenuAeropuertos;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAcerca;
    private javax.swing.JButton jButtonSalirInicio;
    private javax.swing.JButton jButtonSeleccionarInicio;
    private javax.swing.JLabel jLabelBienvenida;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelSeleccione;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JComboBox<String> jMenuAeropuertos;
    // End of variables declaration//GEN-END:variables
}
