/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import business.mainClass;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;


/**
 *
 * @author juansevargas
 */
public final class VentanaAeropuerto0 extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAeropuerto0
     */
    public VentanaAeropuerto0() {
        initComponents();
        setTransparenciaBotones();
        new Thread(new Hilo()).start();
        this.setLocationRelativeTo(null);
    }
    
    public void setTransparenciaBotones()
    {
        jButtonVuelos.setOpaque(false);
        jButtonVuelos.setContentAreaFilled(false);
        jButtonVuelos.setBorderPainted(false);
        
        jButtonUsuario.setOpaque(false);
        jButtonUsuario.setContentAreaFilled(false);
        jButtonUsuario.setBorderPainted(false);
        
        jButtonDirectorio.setOpaque(false);
        jButtonDirectorio.setContentAreaFilled(false);
        jButtonDirectorio.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelFondoAeropuerto0 = new javax.swing.JLabel();
        jLabelTituloAeropuerto0 = new javax.swing.JLabel();
        jLabelCiudad0 = new javax.swing.JLabel();
        jLabelLogoAeropuerto0 = new javax.swing.JLabel();
        jButtonrRegresarIni0 = new javax.swing.JButton();
        jButtonVuelos = new javax.swing.JButton();
        jButtonDirectorio = new javax.swing.JButton();
        jButtonUsuario = new javax.swing.JButton();
        labelHora = new javax.swing.JLabel();
        labelTituloHora = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(760, 590));

        jLabelFondoAeropuerto0.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFondoAeropuerto0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectResources/imgAeropuertoElDorado_1.jpg"))); // NOI18N

        jLabelTituloAeropuerto0.setFont(new java.awt.Font("Seravek", 0, 24)); // NOI18N
        jLabelTituloAeropuerto0.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTituloAeropuerto0.setText("Aeropuerto Internacional El Dorado");

        jLabelCiudad0.setFont(new java.awt.Font("Seravek", 0, 14)); // NOI18N
        jLabelCiudad0.setForeground(new java.awt.Color(204, 204, 255));
        jLabelCiudad0.setText("Bogotá, Colombia");

        jLabelLogoAeropuerto0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectResources/logo3.png"))); // NOI18N

        jButtonrRegresarIni0.setBackground(new java.awt.Color(153, 153, 153));
        jButtonrRegresarIni0.setForeground(new java.awt.Color(0, 51, 51));
        jButtonrRegresarIni0.setText("<Regresar");
        jButtonrRegresarIni0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonrRegresarIni0ActionPerformed(evt);
            }
        });

        jButtonVuelos.setBackground(new java.awt.Color(255, 255, 255));
        jButtonVuelos.setFont(new java.awt.Font("Seravek", 2, 40)); // NOI18N
        jButtonVuelos.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVuelos.setText("Vuelos");
        jButtonVuelos.setOpaque(true);
        jButtonVuelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVuelosActionPerformed(evt);
            }
        });

        jButtonDirectorio.setBackground(new java.awt.Color(255, 255, 255));
        jButtonDirectorio.setFont(new java.awt.Font("Seravek", 2, 40)); // NOI18N
        jButtonDirectorio.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDirectorio.setText("Directorio");
        jButtonDirectorio.setOpaque(true);
        jButtonDirectorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDirectorioActionPerformed(evt);
            }
        });

        jButtonUsuario.setBackground(new java.awt.Color(255, 255, 255));
        jButtonUsuario.setFont(new java.awt.Font("Seravek", 2, 40)); // NOI18N
        jButtonUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jButtonUsuario.setText("Usuario");
        jButtonUsuario.setOpaque(true);
        jButtonUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUsuarioActionPerformed(evt);
            }
        });

        labelHora.setFont(new java.awt.Font("Avenir", 0, 24)); // NOI18N
        labelHora.setForeground(new java.awt.Color(255, 255, 255));

        labelTituloHora.setFont(new java.awt.Font("Avenir", 0, 24)); // NOI18N
        labelTituloHora.setForeground(new java.awt.Color(204, 204, 255));
        labelTituloHora.setText("Hora local:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonrRegresarIni0, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(jLabelLogoAeropuerto0))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jButtonDirectorio, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButtonUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButtonVuelos, javax.swing.GroupLayout.Alignment.LEADING))))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelFondoAeropuerto0)
                                        .addGap(19, 19, 19))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(81, 81, 81)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabelTituloAeropuerto0)
                                            .addComponent(jLabelCiudad0))
                                        .addGap(0, 20, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(labelTituloHora)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelHora, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(23, 23, 23))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelLogoAeropuerto0, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jButtonVuelos))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelFondoAeropuerto0)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonUsuario)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabelTituloAeropuerto0, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelCiudad0)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jButtonDirectorio)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTituloHora, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelHora, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(jButtonrRegresarIni0)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonrRegresarIni0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonrRegresarIni0ActionPerformed
        // TODO add your handling code here:
        ventanaInicio inicio = new ventanaInicio();
        inicio.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonrRegresarIni0ActionPerformed

    private void jButtonVuelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVuelosActionPerformed
        // TODO add your handling code here:
        //Aeropuerto es 0, por tanto la referencia del atributo es 0
        mainClass.cargarVentanaVuelos(0);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonVuelosActionPerformed

    private void jButtonDirectorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDirectorioActionPerformed
        // TODO add your handling code here:
        mainClass.cargarVentanaDirectorio(0);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonDirectorioActionPerformed

    private void jButtonUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUsuarioActionPerformed
        // TODO add your handling code here:
        VentanaUsuarios vuelos = new VentanaUsuarios();
        vuelos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAeropuerto0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAeropuerto0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAeropuerto0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAeropuerto0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAeropuerto0().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDirectorio;
    private javax.swing.JButton jButtonUsuario;
    private javax.swing.JButton jButtonVuelos;
    private javax.swing.JButton jButtonrRegresarIni0;
    private javax.swing.JLabel jLabelCiudad0;
    private javax.swing.JLabel jLabelFondoAeropuerto0;
    private javax.swing.JLabel jLabelLogoAeropuerto0;
    private javax.swing.JLabel jLabelTituloAeropuerto0;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelHora;
    private javax.swing.JLabel labelTituloHora;
    // End of variables declaration//GEN-END:variables
    public class Hilo implements Runnable 
    {

           @Override
           public void run() {
               new Timer(0, new ActionListener() 
               {
                   @Override
                   public void actionPerformed(ActionEvent e) 
                   {
                       Date d = new Date();
                       SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss");
                       labelHora.setText(s.format(d));
                   }
               }).start();
           }
    }
}
